'use client'

import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, ChevronDown, ClipboardCheck, Cloud, Database, FileText, Filter, Laptop, LayoutDashboard, LockKeyhole, Menu, Plus, Search, Server, Settings, Shield, ShieldCheck, Users, X } from 'lucide-react'

type Status = 'Evidence Verified' | 'Needs Review' | 'Potential Gap' | 'Evidence Not Available'
const nav = [
  { label: 'Dashboard', icon: LayoutDashboard }, { label: 'Assessments', icon: ClipboardCheck }, { label: 'Controls', icon: Shield }, { label: 'Potential Gaps', icon: AlertTriangle }, { label: 'Action Plan', icon: BarChart3 },
  { label: 'Assets', icon: Server }, { label: 'Assurance Agents', icon: Activity }, { label: 'Stakeholders', icon: Users }, { label: 'Vendors', icon: Cloud }, { label: 'Recommendations', icon: LockKeyhole }, { label: 'Reports', icon: FileText }, { label: 'Notifications', icon: Bell }, { label: 'Settings', icon: Settings },
]
const assets = [
  ['HR-SERVER-01','AST-001','Server','Windows Server','AGT-001','2 min ago','Evidence Verified','High'], ['STUDENT-ERP-01','AST-002','ERP','Windows Server','AGT-002','4 min ago','Needs Review','High'], ['FILE-SERVER-01','AST-003','File Server','Windows Server','AGT-003','8 min ago','Potential Gap','Critical'], ['DB-SERVER-01','AST-004','Database','Windows Server','AGT-004','12 min ago','Evidence Verified','High'], ['ADMIN-PC-01','AST-005','PC','Windows 11','AGT-005','18 min ago','Evidence Verified','Medium']]
const gaps = [['GAP-012','Backup evidence unavailable','2 assets','High','Open','Verify appropriate backup configuration and recovery procedures.'],['GAP-011','Logging evidence unavailable','4 assets','High','In Progress','Verify logging and monitoring configuration.'],['GAP-009','Vendor retention terms need review','1 vendor','Medium','Open','Review data processing terms and retention commitments.']]
const controls = [['CTRL-SEC-001','Security Safeguards','Technical safeguards requiring review.','Evidence Verified','21 / 25'],['CTRL-ACC-002','Access Control','Privileges and account review controls.','Needs Review','18 / 25'],['CTRL-DAT-003','Data Management','Collection, purpose and minimization.','Evidence Verified','22 / 25'],['CTRL-RET-004','Retention','Retention and secure disposal practices.','Potential Gap','16 / 25'],['CTRL-VND-005','Vendor Assurance','Third-party processing assurance.','Needs Review','19 / 25']]

function Logo(){return <div className="brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span><b>DPDP<span>Guard</span></b><small>ASSURANCE PLATFORM</small></span></div>}
function Badge({status}:{status:string}){let tone=status.includes('Verified')?'green':status.includes('Gap')||status==='Critical'?'red':status.includes('Review')||status==='High'?'amber':'slate';return <span className={`badge ${tone}`}><i/>{status}</span>}
function Stat({label,value,detail,icon:Icon,tone='blue'}:{label:string,value:string,detail:string,icon:any,tone?:string}){return <div className="stat"><span className={`stat-icon ${tone}`}><Icon size={17}/></span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></div>}
function PageTitle({kicker,title,sub,action}:{kicker:string,title:string,sub:string,action?:React.ReactNode}){return <div className="page-title"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Dashboard(){return <><PageTitle kicker="OVERVIEW" title="Good morning, Admin" sub="Here's your current DPDP readiness overview." action={<button className="primary"><Plus size={16}/> Start assessment</button>}/><div className="stats"><Stat label="Overall Readiness" value="78%" detail="+5.2% this month" icon={ShieldCheck}/><Stat label="Total Assets" value="25" detail="22 agents online" icon={Server} tone="indigo"/><Stat label="Evidence Verified" value="18" detail="72% of inventory" icon={CheckCircle2} tone="green"/><Stat label="Potential Gaps" value="2" detail="Requires attention" icon={AlertTriangle} tone="red"/></div><div className="grid-two"><div className="panel readiness"><div className="panel-head"><div><h2>Readiness trend</h2><p>Internal project-defined score</p></div><span className="period">Last 4 months <ChevronDown size={13}/></span></div><div className="trend"><div className="score-ring"><div><strong>78</strong><span>/ 100</span><small>DPDP Readiness</small></div></div><div className="chart"><div className="chart-line"><span style={{height:'38%'}}/><span style={{height:'48%'}}/><span style={{height:'62%'}}/><span style={{height:'75%'}}/></div><div className="chart-labels"><span>Jun<br/><b>61%</b></span><span>Jul<br/><b>68%</b></span><span>Aug<br/><b>73%</b></span><span>Sep<br/><b>78%</b></span></div></div></div><div className="note">Readiness score is based on configured controls and available evidence. It is not an official government score.</div></div><div className="panel"><div className="panel-head"><div><h2>Control categories</h2><p>Evidence coverage by category</p></div><button className="text-button">View controls</button></div><div className="bars">{[['Security','82%'],['Access Control','76%'],['Data Management','80%'],['Retention','65%'],['Vendor Assurance','70%']].map(([x,y])=><div className="bar" key={x}><div><span>{x}</span><b>{y}</b></div><i><em style={{width:y}}/></i></div>)}</div></div></div><div className="grid-two lower"><div className="panel table-panel"><div className="panel-head"><div><h2>Asset status</h2><p>Latest assurance evidence</p></div><button className="text-button">View all assets</button></div><AssetTable compact/></div><div className="panel"><div className="panel-head"><div><h2>Recent activity</h2><p>Latest platform events</p></div><button className="text-button">See all</button></div><div className="activity">{['Agent AGT-001 submitted new evidence','Potential gap detected on FILE-SERVER-01','Vendor review completed','Assessment updated','Backup evidence requires review'].map((x,i)=><div key={x}><span className={`activity-dot d${i}`}/><div><b>{x}</b><small>{i+2} hours ago</small></div></div>)}</div></div></div></>}
function AssetTable({compact=false}:{compact?:boolean}){return <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Agent</th><th>Last check-in</th><th>Status</th></tr></thead><tbody>{assets.slice(0,compact?4:5).map(a=><tr key={a[0]}><td><b>{a[0]}</b><small>{a[1]}</small></td><td>{a[2]}</td><td><span className="online-dot"/>{a[4]}</td><td>{a[5]}</td><td><Badge status={a[6]}/></td></tr>)}</tbody></table></div>}
function Assets(){return <><PageTitle kicker="ASSETS" title="Asset inventory" sub="Discover and monitor the systems that process organizational data." action={<button className="primary"><Plus size={16}/> Register asset</button>}/><div className="toolbar"><div className="search"><Search size={15}/><input placeholder="Search assets..."/></div><button className="filter"><Filter size={14}/> All asset types <ChevronDown size={13}/></button></div><div className="panel"><AssetTable/></div></>}
function Generic({title,label,icon:Icon,sub,children}:{title:string,label:string,icon:any,sub:string,children:React.ReactNode}){return <><PageTitle kicker={label} title={title} sub={sub} action={<button className="primary"><Plus size={16}/> Create new</button>}/>{children||<div className="empty panel"><span><Icon size={25}/></span><h2>Nothing needs your attention</h2><p>As data arrives from your organization, this workspace will update with actionable evidence.</p></div>}</>}
function Gaps(){return <><PageTitle kicker="ASSESSMENT" title="Potential gaps" sub="Review evidence signals that may need remediation."/><div className="summary-row"><Stat label="Critical" value="2" detail="Open gaps" icon={AlertTriangle} tone="red"/><Stat label="High" value="4" detail="Needs attention" icon={AlertTriangle} tone="amber"/><Stat label="Medium" value="6" detail="Being tracked" icon={Activity} tone="indigo"/><Stat label="Low" value="3" detail="Monitor" icon={CheckCircle2} tone="green"/></div><div className="gap-grid">{gaps.map(g=><div className="gap-card panel" key={g[0]}><div className="gap-head"><span className="gap-id">{g[0]}</span><Badge status={g[3]}/></div><h2>{g[1]}</h2><p>{g[5]}</p><div className="gap-meta"><span>Affected assets <b>{g[2]}</b></span><span>Status <Badge status={g[4]}/></span></div><button className="outline">View evidence <ChevronDown size={14}/></button></div>)}</div></>}
function Controls(){return <><PageTitle kicker="ASSESSMENT" title="Control library" sub="Configured controls mapped to organizational and technical evidence."/><div className="toolbar"><div className="search"><Search size={15}/><input placeholder="Search controls..."/></div><button className="filter"><Filter size={14}/> All categories <ChevronDown size={13}/></button></div><div className="control-grid">{controls.map(c=><div className="control-card panel" key={c[0]}><div className="control-top"><span>{c[0]}</span><Badge status={c[3]}/></div><h2>{c[1]}</h2><p>{c[2]}</p><div className="control-foot"><span>Evidence <b>{c[4]}</b></span><button className="text-button">Review <ChevronDown size={12}/></button></div></div>)}</div></>}
function Agents(){return <><PageTitle kicker="ASSURANCE" title="Assurance agents" sub="Windows Services sending technical metadata over authenticated HTTPS." action={<button className="primary"><Plus size={16}/> Add agent</button>}/><div className="stats"><Stat label="Total agents" value="25" detail="Registered" icon={Activity}/><Stat label="Online" value="22" detail="Active now" icon={CheckCircle2} tone="green"/><Stat label="Offline" value="3" detail="Requires attention" icon={AlertTriangle} tone="amber"/></div><div className="panel agent-info"><ShieldCheck size={20}/><div><h2>Privacy by design</h2><p>The agent collects machine identity, OS, encryption, access-control, logging, monitoring, backup indicators and health. It never reads personal documents, emails, chats or file contents.</p></div></div><div className="panel"><AssetTable/></div></>}
function Reports(){return <><PageTitle kicker="REPORTING" title="Reports" sub="Generate evidence-based readiness reports for your review."/><div className="report-grid">{['DPDP Readiness Report','Asset Assurance Report','Control Assessment Report','Gap Analysis Report','Vendor Assurance Report','Evidence History Report'].map((r,i)=><div className="report-card panel" key={r}><span className="report-icon"><FileText size={20}/></span><h2>{r}</h2><p>Includes current assessment, evidence and action items.</p><div><button className="outline">Preview</button><button className="text-button">Generate</button></div></div>)}</div><div className="disclaimer"><LockKeyhole size={16}/><span>This report provides an evidence-based readiness and assurance assessment. It does not constitute legal advice or legal certification of DPDP compliance.</span></div></>}

export default function Page(){const [active,setActive]=useState('Dashboard');const [open,setOpen]=useState(false);const [notice,setNotice]=useState(true);const content=useMemo(()=>{if(active==='Dashboard')return <Dashboard/>;if(active==='Assets')return <Assets/>;if(active==='Potential Gaps')return <Gaps/>;if(active==='Controls')return <Controls/>;if(active==='Assurance Agents')return <Agents/>;if(active==='Reports')return <Reports/>;return <Generic title={active} label={active==='Action Plan'?'REMEDIATION':'ASSURANCE'} icon={nav.find(x=>x.label===active)?.icon||Database} sub="A connected workspace for continuous DPDP readiness and assurance."/>},[active]);return <div className="app"><aside className={`sidebar ${open?'open':''}`}><div className="side-head"><Logo/><button className="close" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="org"><span>AI</span><div><b>ABC Education Institute</b><small>Organization workspace</small></div><ChevronDown size={14}/></div><p className="nav-label">WORKSPACE</p><nav>{nav.map(({label,icon:Icon})=><button key={label} className={active===label?'active':''} onClick={()=>{setActive(label);setOpen(false)}}><Icon size={16}/><span>{label}</span>{['Potential Gaps','Notifications'].includes(label)&&<i className="nav-count">{label==='Potential Gaps'?'2':'5'}</i>}</button>)}</nav><div className="side-foot"><div className="trust"><ShieldCheck size={15}/><span><b>Evidence-first</b><small>Platform status: operational</small></span></div><span className="version">DPDPGuard v1.0</span></div></aside><main><header><div className="crumb"><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu size={20}/></button><span>Workspace</span><i>/</i><b>{active}</b></div><div className="header-right"><div className="global-search"><Search size={14}/><span>Search workspace</span><kbd>⌘ K</kbd></div><Bell size={17}/><span className="avatar">RK</span><b>Rohan Kapoor</b><ChevronDown size={13}/></div></header><div className="content">{notice&&<div className="banner"><span><ShieldCheck size={16}/></span><div><b>Centralized trust boundary</b><p>Endpoints and the frontend communicate only with the Node.js API. MongoDB Atlas credentials stay behind the backend.</p></div><button onClick={()=>setNotice(false)}><X size={15}/></button></div>}{content}</div></main></div>}
